"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _vendor_feed from './vendor-feed.bones.json'
import _item_feed from './item-feed.bones.json'

registerBones({
  "vendor-feed": _vendor_feed,
  "item-feed": _item_feed,
})
