"""Add item_images table

Revision ID: 7ca274f7187f
Revises: e506f0dd739f
Create Date: 2026-05-09 17:59:09.573375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca274f7187f'
down_revision: Union[str, Sequence[str], None] = 'e506f0dd739f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_images_id'), 'item_images', ['id'], unique=False)
    op.execute("""
    INSERT INTO item_images (item_id, image_path, cloudinary_public_id, is_primary)
    SELECT id, image_path, COALESCE(cloudinary_public_id, ''), true
    FROM items
    WHERE image_path IS NOT NULL
""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_images_id'), table_name='item_images')
    op.drop_table('item_images')
    # ### end Alembic commands ###
