"""add reports, vendor blocks, user soft delete

Revision ID: 8b61653ed8e6
Revises: 0379b2326dba
Create Date: 2026-09-29 18:47:41.702555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8b61653ed8e6'
down_revision: Union[str, Sequence[str], None] = '0379b2326dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-trimmed from the autogenerate output: this dev DB has pre-existing
    # drift unrelated to this change (a stale 'vendor_payouts' table from
    # before it was replaced by vendor_wallet_transactions/vendor_withdrawals,
    # a users.is_vendor NOT NULL mismatch, a vendor_subscriptions constraint
    # naming difference) — none of that belongs in a migration about
    # reports/blocks/account deletion, so only the intended changes are kept.
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_item_id'), 'reports', ['item_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_user_id'), 'reports', ['reporter_user_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_vendor_id'), 'reports', ['vendor_id'], unique=False)
    op.create_table('vendor_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vendor_id', name='uq_vendor_block_user_vendor')
    )
    op.create_index(op.f('ix_vendor_blocks_id'), 'vendor_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_blocks_user_id'), 'vendor_blocks', ['user_id'], unique=False)
    op.create_index(op.f('ix_vendor_blocks_vendor_id'), 'vendor_blocks', ['vendor_id'], unique=False)
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_index(op.f('ix_vendor_blocks_vendor_id'), table_name='vendor_blocks')
    op.drop_index(op.f('ix_vendor_blocks_user_id'), table_name='vendor_blocks')
    op.drop_index(op.f('ix_vendor_blocks_id'), table_name='vendor_blocks')
    op.drop_table('vendor_blocks')
    op.drop_index(op.f('ix_reports_vendor_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_item_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
