"""add style cover fields

Revision ID: e1f2g3h4i5j6
Revises: 26ba710e0a08
Create Date: 2026-06-13 19:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f2g3h4i5j6'
down_revision: Union[str, Sequence[str], None] = '26ba710e0a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style_categories', sa.Column('cover_image_path', sa.String(), nullable=True))
    op.add_column('style_categories', sa.Column('cover_cloudinary_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('style_categories', 'cover_cloudinary_id')
    op.drop_column('style_categories', 'cover_image_path')
    # ### end Alembic commands ###
