"""add item_type to items

Revision ID: e506f0dd739f
Revises: de848ceacfdd
Create Date: 2026-04-23 22:56:29.145434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e506f0dd739f'
down_revision: Union[str, Sequence[str], None] = 'de848ceacfdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_items_item_type'), 'items', ['item_type'], unique=False)
    op.drop_constraint(op.f('wardrobe_item_id_fkey'), 'wardrobe', type_='foreignkey')
    op.create_foreign_key(None, 'wardrobe', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wardrobe', type_='foreignkey')
    op.create_foreign_key(op.f('wardrobe_item_id_fkey'), 'wardrobe', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_items_item_type'), table_name='items')
    op.drop_column('items', 'item_type')
    # ### end Alembic commands ###
